# Generated by Django 3.0.6 on 2020-05-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='created_by',
        ),
    ]
