# Generated by Django 3.0.6 on 2020-05-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20200508_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
    ]
